version: '3.5'

services:
  postgres-db:
    image: "postgres:14"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "112233pass"
      PGDATA: "/data/postgres"
    volumes:
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql    
    ports:
      - "5432:5432"
  
 